#     ___      ___       __        __    ___       ___      ___   _______
#    |"  \    /"  |     /""\      |" \  |"  |     |"  \    /"  | /"     "|
#     \   \  //   |    /    \     ||  | ||  |      \   \  //   |(: ______)
#     /\\  \/.    |   /' /\  \    |:  | |:  |      /\\  \/.    | \/    |
#    |: \.        |  //  __'  \   |.  |  \  |___  |: \.        | // ___)_
#    |.  \    /:  | /   /  \\  \  /\  |\( \_|:  \ |.  \    /:  |(:      "|
#    |___|\__/|___|(___/    \___)(__\_|_)\_______)|___|\__/|___| \_______)

# Author Harry0198 / Harolds

#
# ◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥
#                     How to use the plugin
#   Most of this plugin should be self explanatory. Values should
#           be commented out for your ease of use.
#
#   If you're still stuck please refer to the wiki: https://wiki.haroldstudios.com
#
#   Alternatively, see plugin page for more help!
#
# ◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥
#
config-ver: 3

# Disable this plugin's tracking individually here. As a developer I ask you leave this as true
# as it allows me to direct my development focus. However, it is not required.
enable-bstats: true


# This is the default global language that is used across the server if one is not selected
# Default "EN"
lang: "EN"

# Turns debug mode on / off
# Default false (off)
debug: false

date-format: "dd-MM-yyyy"

database:
  type: "json" # json, mysql
  # Drivers
  # com.mysql.cj.jdbc.Driver
  # com.mysql.jdbc.Driver
  driver: "com.mysql.jdbc.Driver"
  database_name: "MailMe"
  host: "localhost"
  port: 3306
  username: "root"
  password: "administrator"
  useSSL: false
  additional_url: ""

# In some cases, it can be useful to have a sending delay. Set minutes until players receive mail.
# Default: 0
send-delay: 0

# Useful for when wanting pickup from post offices ONLY.
mailbox-read-only: false

# Can the player send mail to themselves?
can-send-to-self: true

hooks:
  vault: true # enabled?
  holograms: true

# Requires Vault. Cost for each action
cost:
  message: 25.00
  item: 40.00
  book: 30.00
  set-mailbox: 100.00

# Here, you may add all variations of mailboxes you'd like to add. In this example, a player can only set a mailbox to be a chest
#valid-mailboxes:
#  - CHEST
valid-mailboxes:
  - CHEST

# Distance player has to be within for the mailbox to query the database for unread mail
# and play the ping effect.
# Lower distance usually equals better performance and less strain on database.
mailbox-ping-distance: 50
# Similar to ping except just queries the cache -> less expensive and can be safely altered. But beware of render distance.
mailbox-find-distance: 50

expiry-time-mins: 43200 # 30 days

#                              Icons for usage
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━▼━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#

# Default icons:
# There is no limit to these so you can just add more and it will make new pages like normal.
# If a mistake is made an error will be thrown.
# To add more, simply add another row with your valid material ; modeldata
# If you're not using a custom resource pack, modeldata will not be useful for you and you can set it to 0
# Example: DIRT;0
icons:
  - BLACK_BANNER;0
  - SEA_PICKLE;0
  - ELYTRA;0
  - DIAMOND_PICKAXE;0
  - EMERALD;0
  - MINECART;0
  - DIAMOND;0